# CREATE SCHEMA
CREATE SCHEMA SQL101;

/*
- DATABASE IS A COLLECTION OF TABLES
- MYSQL --> SCHEMA LIKE A FOLDER WITH MULTIPLE RELATED TABLES
*/

# MAKE A SCHEMA DEFAULT
USE SQL101;

# SIMPLE QUERY TO GET DATA 
select * from cars;

# File --> open SQL script --> choose classicmodels.sql

# Once open --> use crtl + A to select entire script 
# then execute using the first execution sign
# click on refresh in schema pane and check if classicmodels is there
# shortcut for execution --> ctrl + shift + enter
# check what are the tables present in this schema

Show tables; # show all tables in the default schema

# DATA QUERY LANGAUGES
/*
SELECT <FIELD LIST>
FROM <TABLES>
JOIN ON
WHERE <CONTITIONAL FILTER>
GROUP BY <AGGREGATION>
HAVING <FILTER ON AGGREGATION>
ORDER BY <SORTING>
LIMIT <NO. OF ROWS>
*/

# GET ALL COLUMNS FROM A TABLE
SELECT * FROM classicmodels.customers;

# DEFAULT SCHEMA IS SET FOR TO CLASSICMODELS
# ALL COLUMNS FROM THE GIVEN TABLE
SELECT * FROM CUSTOMERS;
SELECT "Nimisha" AS FNAME;

# GET 1 COLUMN
SELECT CUSTOMERNAME FROM CUSTOMERS;

# FOR FEW COLUMNS 
SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY
FROM CUSTOMERS;

# CREATE ALIAS FOR COLUMN NAMES IN THE OUTPUT
SELECT CUSTOMERNUMBER AS CUSTNO , CUSTOMERNAME AS NAME, COUNTRY
FROM CUSTOMERS;

# CALCULATE FIELDS
# ORDERDETAILS TABLE : QUANTITY AND PRICEEACH --> TOTAL SALES VALUE
SELECT orderNumber, productCode, (quantityOrdered * priceEach) AS TotalSalesValue
from orderdetails;

SELECT orderNumber, productCode, round(quantityOrdered * priceEach, 1) AS TotalSalesValue
from orderdetails;

# WHERE CLAUSE
-- ALL CUSTOMERS FROM AUSTRALIA
SELECT * FROM CUSTOMERS
WHERE COUNTRY = 'Australia';

 /* comparison operator :
 = : returns true when the value in the row is same as the given value
 <> : returns true when the value in the row is not the same as the given value
<, <= : returns True when the value in the column is less than or less than equals to the given value
>, >= : returns True when the value in the column is greater than or greater than equals to the given value
*/

-- ALL ORDERS WHERE THE TOTAL SALES VALUES IS GREATER THAN 10000
SELECT 
	orderNumber, 
    productCode, 
    (quantityOrdered * priceEach) AS TotalSalesValue
from 
	orderdetails
WHERE (quantityOrdered * priceEach) >= 10000;

# DATES
# ALL ORDERS PLACED BEFORE 1ST JUNE 2003
SELECT * FROM ORDERS
WHERE ORDERDATE < '2003-06-01';

# DATE FORMAT : 'CCYY-MM-DD'
/* LOGICAL OPERATORS :
AND : RETURNS TRUE WHEN BOTH THE COMBINING CONDITIONS ARE TRUE
OR : RETURNS TRUE WHEN EITHER OF THE CONDITION IS TRUE
NOT : NEGATES TRUE --> FALSE AND VICE VERS
*/

-- ALL CUSTOMERS FROM AUSTRALIA AND FRANCE
SELECT * FROM CUSTOMERS
WHERE COUNTRY = 'AUSTRALIA' OR 'FRANCE';

-- ALL THE PRODUCTS OF CLASSIC CARS (PRODUCTLINE) WITH MSRP > 100
SELECT * FROM PRODUCT
WHERE PRODUCTLINE = " Classic Cars" AND MSRP > 100;

-- ALL CUSTOMERS EXCEPT FOR US
SELECT * FROM CUSTOMERS
WHERE COUNTRY <> 'USA';

# IN OPERATOR : MATCH THE VALUE IN A COLUMN TO A LIST OF VALUES

-- AUSTRALIA FRANCE OR SPAIN
SELECT * FROM CUSTOMERS
WHERE COUNTRY = 'AUSTRALIA' OR COUNTRY = 'FRANCE' OR COUNTRY = 'SPAIN';

SELECT * FROM CUSTOMERS
WHERE COUNTRY IN ('AUSTRALIA','FRANCE','SPAIN');

SELECT * FROM CUSTOMERS
WHERE COUNTRY NOT IN ('AUSTRALIA','FRANCE','SPAIN');

SELECT * FROM CUSTOMERS
WHERE NOT COUNTRY IN ('AUSTRALIA','FRANCE','SPAIN');

# BETWEEN OPERATOR : FOR RANGE OF VALUES (DATE RANGE OR NUMERIC RANGE)
SELECT * FROM PRODUCTS
WHERE MSRP BETWEEN 100 AND 200;

SELECT * FROM PRODUCTS
WHERE MSRP >= 100 AND MSRP <= 200;

SELECT * FROM PRODUCTS
WHERE NOT MSRP BETWEEN 100 AND 200; # BOTH INCLUSIVE

SELECT * FROM ORDERS
WHERE ORDERDATE >= '2003-01-01' AND ORDERDATE < '2003-02-15';

SELECT * FROM ORDERS
WHERE ORDERDATE BETWEEN '2003-01-01' AND '2003-02-15';

# LIKE : PATTERN MATCHING IN TEXT

-- NEED ALL CUSTOMERS WHO HAS GIFTS IN THEIR NAMES
/* WILD CARD MATCHING 
% : MATCHES TO ZERO OR MORE CHARACTER
_ : MATCHES TO 1 CHARACTER
*/

-- PICK UP ALL EMPLOYEES WHOSE FIRST NAME START WITH A
-- IT CAN BE FOLLOWED BY ZERO OR MORE CHARACTER

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME LIKE "A%";

# FOUR LETTER NAMES STARTING WITH A
SELECT * FROM EMPLOYEES
WHERE FIRSTNAME LIKE "A___"

# GET ALL CUSTOMERS WHICH HAVE 'Gift' IN THEIR NAMES
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%GIFT%';

-- GROUP BY AGGREGATION
-- HAVING
-- ORDER BY AND LIMIT

# ORDER OF WRITING A SQL QUERY
/*
SELECT 
FROM 
WHERE 
GROUP BY
HAVING 
ORDER BY
LIMIT
*/

-- EXECUTION ORDER
/*
TABLES ARE IDENTIFIED : FROM
CONDITIONAL FILTERING : WHERE | WORKS ON THE SOURCE DATA
AGGREGATION OF DATA : GROUP BY
AGGREGATION FILTERS : HAVING | WORK ON FINAL AGGREGATED DATA
FINALIZING THE FIELDS IN THE RESULT : SELECT
ORDER BY AND LIMIT
*/



